# Configuration for Whisper inference experiments

# ============================================================
# Setup
# ============================================================

seed: 42


# ============================================================
# Data
# ============================================================

data:
  dataset_path: data/
  test_set: test_vienna.csv

  audio_column: audio
  text_column: sentence

  sampling_rate: 16000


# ============================================================
# Whisper
# ============================================================

whisper:
  model: small
  path: openai/whisper-
  language: english
  task: transcribe


# ============================================================
# Approach
# ============================================================

model:
  # possible:
  # - whisper
  # - deep_fusion
  # - shallow_fusion
  type: whisper


# ============================================================
# Shallow Fusion
# ============================================================

shallow_fusion:
  lm:
    name: gpt2
    path: 

  weight: 0.1


# ============================================================
# Deep Fusion
# ============================================================

deep_fusion:
  use_lm: false

  copy_weights: true

  lm:
    name: gpt2
    path: 

  model:
    name: df_copyw_medium_NoLM_1e-05w100_coarse_train25p_pkv_dec
    path: models/deep_fusion/


# ============================================================
# Generation
# ============================================================

generation:
  num_beams: 1
  max_length: 225


# ============================================================
# Inference
# ============================================================

inference:
  batch_size: 1


# ============================================================
# Output
# ============================================================

output:
  path: results/